language: ruby
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4.1.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5.0.x

rvm: 
  - 2.0.0
  - 2.2.4
  - 2.3.0
gemfile:
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-3.2.x
